### ISSUE TITLE
Add other Jobs to see Robberys

### ISSUE THREAD

**Issue by MVSTYYY** [HumanTree92/esx_advancedholdup#15]
**Describe the Bug | A Clear & Concise Description of Bug**
How can i add other Jobs to see the robberys like lssd or FIB?

**Questions**
Have you made changes to anything besides the `config.lua`?: Yes
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy?: Yes
Are you using OneSync?: Onesync Infinity
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_advancedholdup/blob/master/server/main.lua#L75 This is where it gets the police job. On how to set it up to allow multiple jobs I'm not sure.
