### ISSUE TITLE
Script error in code

### ISSUE THREAD

**Issue by CapitalistNick** [HumanTree92/esx_advancedholdup#2]
Creating script environments for esx_advancedholdup
Error loading script server/main.lua in resource esx_advancedholdup: @esx_advancedholdup/server/main.lua:25: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
	@esx_advancedholdup/server/main.lua:25: in main chunk
Failed to load script server/main.lua.
Started resource esx_advancedholdup

**Comment by HumanTree92** [comment]
Update to ESX V1 or ExtendedMode
