### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wolgix** [HumanTree92/esx_advancedholdup#3]
**Describe the Bug | A Clear & Concise Description of Bug**

Error loading script server/main.lua in resource esx_advancedholdup: @esx_advancedholdup/server/main.lua:25: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
@esx_advancedholdup/server/main.lua:25: in main chunk
Failed to load script server/main.lua.

**Questions**
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: ye
What Version of es_extended are you using?: old one (limit)
Are you using a Pre-Installed ESX?: no
Are you using Essentialmode?: yes
Are you using OneSync?: yes
Linux or Windows?: linux

**Comment by HumanTree92** [comment]
You have a few options:
1. You can either update to ESX V1 Finale or ExtendedMode.
2. You can re-write the commands to work with your version.
3. You can comment out the Commands
