### ISSUE TITLE
No Blips or Markers to start robbery are showing

### ISSUE THREAD

**Issue by Deus1855** [HumanTree92/esx_advancedholdup#5]
**Describe the Bug | A Clear & Concise Description of Bug**
I have both requirements for this Script es_extended V1 Final and esx_policejob. Added this to the /resource folder and added start esx_advancedholdup to the server.cfg file after making sure both es_extended and esx_policejob. The server says it starts the resource. I load into the game and head over to the XYZ coords where the robbery should be doable. Nothing is there, No blip or marker, No "press E to rob" type of trigger or anything. I went to multiple XYZ Coords provided within the script and no shop or bank has anything that says they can be robbed. 

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:   No Changes have been made
Have you looked through the Closed Topics?:  Dont see any for this particular script
Have you looked through the Wiki?:  Read Through wiki only shows help for advanced garage and extraitems scripts. 
Are you using a Pre-Installed ESX? If Yes who?:  I Use Esx V1 Final
Are you using es_extended? If Yes what Version? (Example: 1.2):   I Use Esx V1 Final
Are you using Essentialmode?:  No
Are you using ExtendedMode?:  No
Are you using OneSync?:  No
Linux or Windows?:  Windows

**Comment by HumanTree92** [comment]
Markers & blips only show up if the required Police are on. Take a look at this https://github.com/HumanTree92/esx_advancedholdup/blob/master/config.lua#L17 setting this to 0 will result in players being able to Rob without cops on. You must also have a weapon out as shown here https://github.com/HumanTree92/esx_advancedholdup/blob/master/client/main.lua#L165
