### ISSUE TITLE
[  script:es_extended] es_extended: TriggerServerCallback => [esx_advancedholdup:checkRob] does not exist

### ISSUE THREAD

**Issue by ElectriziaDev** [HumanTree92/esx_advancedholdup#8]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: no
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): yes 1 final
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

Hello !
I've this error :
[  script:es_extended] es_extended: TriggerServerCallback => [esx_advancedholdup:checkRob] does not exist

I've check the script and i do not find a function for "checkRob". 
It's an error maybe ?

Good day !

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_advancedholdup/blob/master/server/main.lua#L35
